myscrumy/django-jeremiahscrumy/jeremiahscrumy/urls.py
from django.urls import include, path
from . import views

app_name = 'jeremiahscrumy'

urlpatterns = [
    path('', views.index, name="index"),

    path('movegoal/<int:goal_id>/', views.move_goal, name="movegoal"),

    path('addgoal/', views.add_goal, name="addgoal"),

    path('home/', views.home, name="home"),

    path('accounts/', include('django.contrib.auth.urls')),
]

myscrumy/jeremiahscrumy/urls.py
from django.urls import include, path
from . import views

app_name = 'jeremiahscrumy'

urlpatterns = [
    path('', views.index, name="index"),

    path('movegoal/<int:goal_id>/', views.move_goal, name="movegoal"),

    path('addgoal/', views.add_goal, name="addgoal"),

    path('home/', views.home, name="home"),

    path('accounts/', include('django.contrib.auth.urls')),
]

myscrumy/myscrumy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jeremiahscrumy/', include('jeremiahscrumy.urls', namespace='jeremiahscrumy')),
    path('websocket/', include('websocket.urls', namespace='websocket')),
]

# urlpatterns += staticfiles_urlpatterns()

myscrumy/django-jeremiahscrumy/jeremiahscrumy/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class GoalStatus(models.Model):
    status_name = models.CharField(max_length=250)

    def __str__(self):
        return self.status_name


class ScrumyGoals(models.Model):
    goal_name = models.CharField(max_length=250)
    goal_id = models.IntegerField(default=1)
    created_by = models.CharField(max_length=250)
    moved_by = models.CharField(max_length=250)
    owner = models.CharField(max_length=250)
    goal_status = models.ForeignKey(
        GoalStatus, on_delete=models.PROTECT, null=True)
    user = models.ForeignKey(User, related_name='user',
                             on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.goal_name


class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length=250)
    created_by = models.CharField(max_length=250)
    moved_from = models.CharField(max_length=250)
    moved_to = models.CharField(max_length=250)
    time_of_action = models.DateTimeField(auto_now_add=True, null=True)
    goal = models.ForeignKey(
        ScrumyGoals, on_delete=models.PROTECT)

    def __str__(self):
        return self.created_by

myscrumy/django-jeremiahscrumy/jeremiahscrumy/forms.py
from django.forms import ModelForm, TextInput
from django.contrib.auth.models import User
from .models import ScrumyGoals


class SignupForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']


class CreateGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'user']

myscrumy/jeremiahscrumy/forms.py
from django.forms import ModelForm, TextInput
from django.contrib.auth.models import User
from .models import ScrumyGoals


class SignupForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']


class CreateGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'user']

myscrumy/django-jeremiahscrumy/jeremiahscrumy/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from .models import ScrumyGoals, GoalStatus
from django.contrib.auth.models import User, Group
from .forms import SignupForm, CreateGoalForm
import random

# Create your views here.


def index(request):
    # goal = ScrumyGoals.objects.filter(goal_name='Learn Django')
    # return HttpResponse(goal)

    form = SignupForm()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        form.save()
        user = User.objects.get(username=request.POST['username'])
        my_group = Group.objects.get(name='Developer')
        my_group.user_set.add(user)

        if user.groups.filter(name='Developer').exists():
            return render(request, 'jeremiahscrumy/welcome.html')
    else:
        form = SignupForm()

    context = {'form': form}

    return render(request, 'jeremiahscrumy/index.html', context)


def add_goal(request):

    # rand_num = random.randrange(1000, 9999, 1)
    # my_user = User.objects.get(username='louis')
    # weekly_goal = GoalStatus.objects.get(status_name='Weekly Goal')

    # goal_added = ScrumyGoals.objects.create(goal_name='Keep Learning Django', goal_id=rand_num, created_by='Louis',
    #                                         moved_by='Louis', owner='Louis', goal_status=weekly_goal, user=my_user)
    # return HttpResponse(goal_added)

    form = CreateGoalForm()
    if request.method == 'POST':
        form = CreateGoalForm(request.POST)
        good_to_go = form.save(commit=False)
        good_to_go.goal_id = random.randrange(1000, 9999, 1)
        good_to_go.created_by = 'Louis'
        good_to_go.moved_by = 'Louis'
        good_to_go.owner = 'Louis'
        good_to_go.goal_status = GoalStatus(status_name='Weekly Goal')
        good_to_go.goal_status.save()
        good_to_go.save()

    else:
        form = CreateGoalForm()

    context = {'form': form}

    return render(request, 'jeremiahscrumy/goal.html', context)


def move_goal(request, **kwargs):
    # try:
    #     goal = ScrumyGoals.objects.get(goal_id=goal_id)
    # except ScrumyGoals.DoesNotExist:
    #     raise Http404("A record with that goal id does not exist")

    #     context = {'error': goal}
    #     return render(request, 'jeremiahscrumy/exception.html', context)
    # else:
    #     return HttpResponse(goal.goal_name)

    dictionary = {'result': 'Success'}
    if request.method == 'POST':
        if request.user.groups.filter(name="Developer").exists():
            obj = ScrumyGoals.objects.get(goal_id=kwargs['goal_id'])
            if request.user == obj.user:
                if request.POST['goal_status'] == 'Done Goal':
                    return HttpResponse('You are a developer')
                else:
                    obj.goal_status = GoalStatus(
                        status_name=request.POST['goal_status'])
                    obj.goal_status.save()
                    obj.save()
                    return render(request, 'jeremiahscrumy/exception.html', dictionary)
            else:
                return HttpResponse('Not the owner')
        elif request.user.groups.filter(name='Quality Assurance').exists():
            obj = ScrumyGoals.objects.get(goal_id=kwargs["goal_id"])
            if request.user == obj.user:
                obj.goal_status = GoalStatus(
                    status_name=request.POST['goal_status'])
                obj.goal_status.save()
                obj.save()
                return render(request, 'jeremiahscrumy/exception.html', dictionary)
            else:
                if request.POST['goal_status'] == "Done Goal":
                    obj.goal_status = GoalStatus(
                        status_name=request.POST['goal_status'])
                    obj.goal_status.save()
                    obj.save()
                    return render(request, 'jeremiahscrumy/exception.html', dictionary)
                else:
                    return HttpResponse('Not the owner')
        elif request.user.groups.filter(name='Owner').exists():
            obj = ScrumyGoals.objects.get(goal_id=kwargs["goal_id"])
            if request.user == obj.user:
                obj.goal_status = GoalStatus(
                    status_name=request.POST['goal_status'])
                obj.goal_status.save()
                obj.save()
                return render(request, 'jeremiahscrumy/exception.html', dictionary)
            else:
                return HttpResponse('Not the owner')
        elif request.user.groups.filter(name='Admin').exists():
            obj = ScrumyGoals.objects.get(goal_id=kwargs["goal_id"])
            obj.goal_status = GoalStatus(
                status_name=request.POST['goal_status'])
            obj.goal_status.save()
            obj.save()
            return render(request, 'jeremiahscrumy/exception.html', dictionary)
        else:
            return render(request, 'jeremiahscrumy/exception.html')
    else:
        return render(request, 'jeremiahscrumy/exception.html')


def home(request):
    dictionary = {}
    users = User.objects.all()
    weekly_goals = ScrumyGoals.objects.filter(
        goal_status=GoalStatus.objects.get(status_name='Weekly Goal'))
    daily_goals = ScrumyGoals.objects.filter(
        goal_status=GoalStatus.objects.get(status_name='Daily Goal'))
    verify_goals = ScrumyGoals.objects.filter(
        goal_status=GoalStatus.objects.get(status_name='Verify Goal'))
    done_goals = ScrumyGoals.objects.filter(
        goal_status=GoalStatus.objects.get(status_name='Done Goal'))

    dictionary['weekly_goals'] = '  '.join(
        [eachgoal_1.goal_name for eachgoal_1 in weekly_goals])
    dictionary['daily_goals'] = '  '.join(
        [eachgoal_1.goal_name for eachgoal_1 in daily_goals])
    dictionary['verify_goals'] = '  '.join(
        [eachgoal_1.goal_name for eachgoal_1 in verify_goals])
    dictionary['done_goals'] = '  '.join(
        [eachgoal_1.goal_name for eachgoal_1 in done_goals])

    dictionary['users'] = users

    dictionary['user_real'] = '  '.join(
        [eachgoal_1.username for eachgoal_1 in users])
    return render(request, 'jeremiahscrumy/home.html', dictionary)

    # my_users = User.objects.all()
    # my_first_user = my_users[0]
    # my_goals = my_first_user.user.all()
    # goal_status = GoalStatus.objects.all()
    # weekly_goal = goal_status[0]
    # daily_goal = goal_status[1]
    # verify_goal = goal_status[2]
    # done_goal = goal_status[3]

    # dictionary = {
    #     'my_first_user': my_first_user,
    #     'weekly_goal': weekly_goal,
    #     'daily_goal': daily_goal,
    #     'verify_goal': verify_goal,
    #     'done_goal': done_goal,
    #     'my_goals': my_goals,
    #     'my_users': my_users,
    # }

    return render(request, 'jeremiahscrumy/home.html', dictionary)

myscrumy/jeremiahscrumy/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from .models import ScrumyGoals, GoalStatus
from django.contrib.auth.models import User, Group
from .forms import SignupForm, CreateGoalForm
import random

# Create your views here.


def index(request):
    # goal = ScrumyGoals.objects.filter(goal_name='Learn Django')
    # return HttpResponse(goal)

    form = SignupForm()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        form.save()
        user = User.objects.get(username=request.POST['username'])
        my_group = Group.objects.get(name='Developer')
        my_group.user_set.add(user)

        if user.groups.filter(name='Developer').exists():
            return render(request, 'jeremiahscrumy/welcome.html')
    else:
        form = SignupForm()

    context = {'form': form}

    return render(request, 'jeremiahscrumy/index.html', context)


def add_goal(request):

    # rand_num = random.randrange(1000, 9999, 1)
    # my_user = User.objects.get(username='louis')
    # weekly_goal = GoalStatus.objects.get(status_name='Weekly Goal')

    # goal_added = ScrumyGoals.objects.create(goal_name='Keep Learning Django', goal_id=rand_num, created_by='Louis',
    #                                         moved_by='Louis', owner='Louis', goal_status=weekly_goal, user=my_user)
    # return HttpResponse(goal_added)

    form = CreateGoalForm()
    if request.method == 'POST':
        form = CreateGoalForm(request.POST)
        good_to_go = form.save(commit=False)
        good_to_go.goal_id = random.randrange(1000, 9999, 1)
        good_to_go.created_by = 'Louis'
        good_to_go.moved_by = 'Louis'
        good_to_go.owner = 'Louis'
        good_to_go.goal_status = GoalStatus(status_name='Weekly Goal')
        good_to_go.goal_status.save()
        good_to_go.save()

    else:
        form = CreateGoalForm()

    context = {'form': form}

    return render(request, 'jeremiahscrumy/goal.html', context)


def move_goal(request, **kwargs):
    # try:
    #     goal = ScrumyGoals.objects.get(goal_id=goal_id)
    # except ScrumyGoals.DoesNotExist:
    #     raise Http404("A record with that goal id does not exist")

    #     context = {'error': goal}
    #     return render(request, 'jeremiahscrumy/exception.html', context)
    # else:
    #     return HttpResponse(goal.goal_name)

    dictionary = {'result': 'Success'}
    if request.method == 'POST':
        if request.user.groups.filter(name="Developer").exists():
            obj = ScrumyGoals.objects.get(goal_id=kwargs['goal_id'])
            if request.user == obj.user:
                if request.POST['goal_status'] == 'Done Goal':
                    return HttpResponse('You are a developer')
                else:
                    obj.goal_status = GoalStatus(
                        status_name=request.POST['goal_status'])
                    obj.goal_status.save()
                    obj.save()
                    return render(request, 'jeremiahscrumy/exception.html', dictionary)
            else:
                return HttpResponse('Not the owner')
        elif request.user.groups.filter(name='Quality Assurance').exists():
            obj = ScrumyGoals.objects.get(goal_id=kwargs["goal_id"])
            if request.user == obj.user:
                obj.goal_status = GoalStatus(
                    status_name=request.POST['goal_status'])
                obj.goal_status.save()
                obj.save()
                return render(request, 'jeremiahscrumy/exception.html', dictionary)
            else:
                if request.POST['goal_status'] == "Done Goal":
                    obj.goal_status = GoalStatus(
                        status_name=request.POST['goal_status'])
                    obj.goal_status.save()
                    obj.save()
                    return render(request, 'jeremiahscrumy/exception.html', dictionary)
                else:
                    return HttpResponse('Not the owner')
        elif request.user.groups.filter(name='Owner').exists():
            obj = ScrumyGoals.objects.get(goal_id=kwargs["goal_id"])
            if request.user == obj.user:
                obj.goal_status = GoalStatus(
                    status_name=request.POST['goal_status'])
                obj.goal_status.save()
                obj.save()
                return render(request, 'jeremiahscrumy/exception.html', dictionary)
            else:
                return HttpResponse('Not the owner')
        elif request.user.groups.filter(name='Admin').exists():
            obj = ScrumyGoals.objects.get(goal_id=kwargs["goal_id"])
            obj.goal_status = GoalStatus(
                status_name=request.POST['goal_status'])
            obj.goal_status.save()
            obj.save()
            return render(request, 'jeremiahscrumy/exception.html', dictionary)
        else:
            return render(request, 'jeremiahscrumy/exception.html')
    else:
        return render(request, 'jeremiahscrumy/exception.html')


def home(request):
    dictionary = {}
    users = User.objects.all()
    weekly_goals = ScrumyGoals.objects.filter(
        goal_status=GoalStatus.objects.get(status_name='Weekly Goal'))
    daily_goals = ScrumyGoals.objects.filter(
        goal_status=GoalStatus.objects.get(status_name='Daily Goal'))
    verify_goals = ScrumyGoals.objects.filter(
        goal_status=GoalStatus.objects.get(status_name='Verify Goal'))
    done_goals = ScrumyGoals.objects.filter(
        goal_status=GoalStatus.objects.get(status_name='Done Goal'))

    dictionary['weekly_goals'] = '  '.join(
        [eachgoal_1.goal_name for eachgoal_1 in weekly_goals])
    dictionary['daily_goals'] = '  '.join(
        [eachgoal_1.goal_name for eachgoal_1 in daily_goals])
    dictionary['verify_goals'] = '  '.join(
        [eachgoal_1.goal_name for eachgoal_1 in verify_goals])
    dictionary['done_goals'] = '  '.join(
        [eachgoal_1.goal_name for eachgoal_1 in done_goals])

    dictionary['users'] = users

    dictionary['user_real'] = '  '.join(
        [eachgoal_1.username for eachgoal_1 in users])
    return render(request, 'jeremiahscrumy/home.html', dictionary)

    # my_users = User.objects.all()
    # my_first_user = my_users[0]
    # my_goals = my_first_user.user.all()
    # goal_status = GoalStatus.objects.all()
    # weekly_goal = goal_status[0]
    # daily_goal = goal_status[1]
    # verify_goal = goal_status[2]
    # done_goal = goal_status[3]

    # dictionary = {
    #     'my_first_user': my_first_user,
    #     'weekly_goal': weekly_goal,
    #     'daily_goal': daily_goal,
    #     'verify_goal': verify_goal,
    #     'done_goal': done_goal,
    #     'my_goals': my_goals,
    #     'my_users': my_users,
    # }

    return render(request, 'jeremiahscrumy/home.html', dictionary)

myscrumy/jeremiahscrumy/templates/jeremiahscrumy/exception.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>

<body>
    {% block content %}
    <p>{{ obj }}</p>
    {% endblock %}
</body>

</html>

myscrumy/jeremiahscrumy/templates/jeremiahscrumy/goal.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Goal</title>
</head>

<body>
    <a href="{% url 'jeremiahscrumy:index' %}">About us</a>
    <form action="" method="POST">
        <Label>Goal name:
            <br>
            <input type="text">
        </Label><br>
        <label for="">User:
            <br>
            <select style="width:175px" name="" id="">
                <option value="">-------------------</option>
            </select>
        </label>
    </form>
</body>

</html>

myscrumy/jeremiahscrumy/templates/jeremiahscrumy/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>

    <style>
        table,
        th,
        td {
            border: 1px solid #2f2f2f;
        }
    </style>
</head>

<body>
    <a href="{% url 'jeremiahscrumy:addgoal' %}">Home</a>

    <br />

    <!-- <table>
        <thead>
            <tr>
                <th>Users</th>
                <th>Weekly Goals</th>
                <th>Daily Goals</th>
                <th>Verify Goals</th>
                <th>Done Goals</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                {% for obj in my_users %}
                <td>{{obj}}</td>
                {% for goal in obj.user.all %}
                {%if goal.goal_status.status_name == 'Weekly Goal'%}
                <td> {{goal.goal_id}} {{goal.goal_name}}</td>
                <td></td>
                <td></td>
                <td></td>
                {%elif goal.goal_status.status_name == 'Daily Goal'%}
                <td> </td>
                <td>{{goal.goal_id}} {{goal.goal_name}}</td>
                <td></td>
                <td></td>
                {%elif goal.goal_status.status_name == 'Verify Goal'%}
                <td></td>
                <td></td>
                <td>{{goal.goal_id}} {{goal.goal_name}}</td>
                <td></td>
                {%else%}
                <td></td>
                <td></td>
                <td></td>
                <td>{{goal.goal_id}} {{goal.goal_name}}</td>
                {%endif%}
            </tr>
            {% endfor %}
            {% endfor %}
        </tbody>
    </table> -->

    <table>
        <thead>
            <tr>
                <th>Users</th>
                <th>Weekly Goals</th>
                <th>Daily Goals</th>
                <th>Verify Goals</th>
                <th>Done Goals</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user }}</td>
                {% for goal in user.user.all %}
                {% if goal.goal_status.status_name == 'Weekly Goal' %}
                <td></td>
                <td> {{goal.goal_id}} {{goal.goal_name}}</td>
                {% elif goal.goal_status.status_name == 'Daily Goal' %}
                <td></td>
                <td>{{goal.goal_id}} {{goal.goal_name}}</td>
                {%elif goal.goal_status.status_name == 'Verify Goal'%}
                <td></td>
                <td></td>
                <td>{{goal.goal_id}} {{goal.goal_name}}</td>
                {%else%}
                <td></td>
                <td></td>
                <td></td>
                <td>{{goal.goal_id}} {{goal.goal_name}}</td>
                {%endif%}
            </tr>
            {% endfor %}
            {% endfor %}
        </tbody>
    </table>

</body>

</html>

myscrumy/jeremiahscrumy/templates/jeremiahscrumy/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
</head>

<body>
    <a href="{% url 'jeremiahscrumy:index' %}">About us</a>
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <button>Sign up</button>
    </form>
</body>

</html>

myscrumy/jeremiahscrumy/templates/jeremiahscrumy/welcome.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
</head>

<body>
    <p>Your account has been created successfully</p>
</body>

</html>